import re
import tempfile
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Image as RLImage, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def create_pdf(report, image=None, summary=None):
    file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(
        file.name,
        pagesize=A4,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.8 * inch,
        bottomMargin=0.8 * inch,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=10,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceAfter=10,
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=18,
        textColor=colors.HexColor("#0369A1"),
        spaceBefore=8,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "SectionBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#111827"),
        spaceAfter=6,
    )

    content = []

    content.append(Paragraph("AI Infrastructure Inspection Report", title_style))
    content.append(Paragraph("Generated by Civil-AI-Agent", subtitle_style))
    content.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.HexColor("#CBD5E1"),
            spaceBefore=4,
            spaceAfter=10,
        )
    )

    if summary:
        generated_at = summary.get("generated_at") or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        table_data = [
            ["Metric", "Value"],
            ["Image", str(summary.get("image_name", "N/A"))],
            ["Total Cracks", str(summary.get("total_cracks", 0))],
            ["High Severity", str(summary.get("high_severity", 0))],
            ["Generated At", generated_at],
        ]
        summary_table = Table(table_data, colWidths=[2.0 * inch, 4.2 * inch])
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        content.append(summary_table)
        content.append(Spacer(1, 10))

    if image is not None:
        img_path = tempfile.NamedTemporaryFile(delete=False, suffix=".jpg").name
        image.save(img_path)
        content.append(RLImage(img_path, width=6.2 * inch, height=3.6 * inch))
        content.append(Spacer(1, 10))

    for raw_line in report.split("\n"):
        line = raw_line.strip()
        if not line:
            content.append(Spacer(1, 4))
            continue

        if re.match(r"^\d+[\.)]\s+", line) or line.lower().endswith(":"):
            content.append(Paragraph(line, heading_style))
            continue

        content.append(Paragraph(line, body_style))

    doc.build(content)
    return file.name