import re
import tempfile
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image as RLImage,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _md_to_rl(text: str) -> str:
    """Convert **bold** and *italic* markdown to ReportLab XML tags."""
    import re as _re
    text = _re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = _re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    return text


def create_pdf(report, image=None, summary=None):
    file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(
        file.name,
        pagesize=A4,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.8 * inch,
        bottomMargin=0.8 * inch,
    )
    styles = getSampleStyleSheet()

    h1_style = ParagraphStyle(
        "ReportH1",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=28,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=4,
    )
    h2_style = ParagraphStyle(
        "ReportH2",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=22,
        textColor=colors.HexColor("#0369A1"),
        spaceBefore=14,
        spaceAfter=4,
        borderPad=0,
    )
    h3_style = ParagraphStyle(
        "ReportH3",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=17,
        textColor=colors.HexColor("#0F4C81"),
        spaceBefore=10,
        spaceAfter=3,
    )
    h4_style = ParagraphStyle(
        "ReportH4",
        parent=styles["Heading4"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#1E3A8A"),
        spaceBefore=8,
        spaceAfter=2,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "SectionBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#111827"),
        spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "BulletBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#111827"),
        leftIndent=16,
        spaceAfter=4,
    )

    content = []

    content.append(Paragraph("AI Infrastructure Inspection Report", h1_style))
    content.append(Paragraph("Generated by Civil-AI-Agent", subtitle_style))
    content.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.HexColor("#CBD5E1"),
            spaceBefore=4,
            spaceAfter=10,
        )
    )

    if summary:
        generated_at = summary.get("generated_at") or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        table_data = [
            ["Metric", "Value"],
            ["Image", str(summary.get("image_name", "N/A"))],
            ["Total Cracks", str(summary.get("total_cracks", 0))],
            ["High Severity", str(summary.get("high_severity", 0))],
            ["Generated At", generated_at],
        ]
        summary_table = Table(table_data, colWidths=[2.0 * inch, 4.2 * inch])
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        content.append(summary_table)
        content.append(Spacer(1, 10))

    if image is not None:
        img_path = tempfile.NamedTemporaryFile(delete=False, suffix=".jpg").name
        image.save(img_path)
        content.append(RLImage(img_path, width=6.2 * inch, height=3.6 * inch))
        content.append(Spacer(1, 10))

    # --- parse markdown report ---
    bullet_buffer: list[ListItem] = []

    def _flush_bullets() -> None:
        if bullet_buffer:
            content.append(
                ListFlowable(
                    bullet_buffer[:],
                    bulletType="bullet",
                    bulletFontName="Helvetica",
                    bulletFontSize=10,
                    bulletColor=colors.HexColor("#0369A1"),
                    leftIndent=20,
                    spaceBefore=2,
                    spaceAfter=6,
                )
            )
            bullet_buffer.clear()

    for raw_line in report.split("\n"):
        line = raw_line.rstrip()
        stripped = line.lstrip()

        # Markdown headings  →  ##, ###, ####, #####, ######
        heading_match = re.match(r"^(#{2,6})\s+(.+)$", stripped)
        if heading_match:
            _flush_bullets()
            level = len(heading_match.group(1))
            heading_text = _md_to_rl(heading_match.group(2).strip())

            if level == 2:
                content.append(Paragraph(heading_text, h2_style))
                content.append(
                    HRFlowable(width="100%", thickness=0.75, color=colors.HexColor("#BAE6FD"), spaceAfter=4)
                )
            elif level == 3:
                content.append(Paragraph(heading_text, h3_style))
            else:
                content.append(Paragraph(heading_text, h4_style))
            continue

        # Bullet  →  - text  or  * text
        if stripped.startswith("- ") or stripped.startswith("* "):
            bullet_text = _md_to_rl(stripped[2:].strip())
            bullet_buffer.append(
                ListItem(Paragraph(bullet_text, bullet_style), leftIndent=12)
            )
            continue

        # Flush pending bullets before a non-bullet line
        _flush_bullets()

        if not stripped:
            content.append(Spacer(1, 4))
            continue

        content.append(Paragraph(_md_to_rl(stripped), body_style))

    _flush_bullets()

    doc.build(content)
    return file.name